//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arma3BE.Models
{
    public partial class ChatLog
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public System.Guid ServerId { get; set; }
        public System.DateTime Date { get; set; }
    }
}
