//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Arma3BE.Models
{
    public partial class Note
    {   
        public System.Guid Id { get; set; }
        public System.Guid PlayerId { get; set; }
        public string Text { get; set; }
        public System.DateTime Date { get; set; }
        public virtual Player Player { get; set; }
    }
}
